from enum import Enum


class HatchStyleEnum(str, Enum):
    CROSS = "CROSS"
    DIAGONAL_CROSS = "DIAGONAL_CROSS"
    DIAGONAL_LEFT = "DIAGONAL_LEFT"
    DIAGONAL_RIGHT = "DIAGONAL_RIGHT"
    DIAGONAL_RIGHT_DENSE = "DIAGONAL_RIGHT_DENSE"
    DIAGONAL_WITH_DOTS = "DIAGONAL_WITH_DOTS"
    DOTS = "DOTS"
    DOTS_DENSE = "DOTS_DENSE"
    HORIZONTAL = "HORIZONTAL"
    HORIZONTAL_CONTINUOUS_AND_DASHED = "HORIZONTAL_CONTINUOUS_AND_DASHED"
    HORIZONTAL_DENSE = "HORIZONTAL_DENSE"
    HORIZONTAL_WAVY = "HORIZONTAL_WAVY"
    HORIZONTAL_WITH_ARROWS_INTERVAL = "HORIZONTAL_WITH_ARROWS_INTERVAL"
    HORIZONTAL_WITH_BIG_CROSS_INTERVAL = "HORIZONTAL_WITH_BIG_CROSS_INTERVAL"
    HORIZONTAL_WITH_SPARSE_SMALL_CROSSES_INTERVAL = "HORIZONTAL_WITH_SPARSE_SMALL_CROSSES_INTERVAL"
    LARGE_CIRCLES = "LARGE_CIRCLES"
    LARGE_CROSS = "LARGE_CROSS"
    SMALL_CIRCLES = "SMALL_CIRCLES"
    SMALL_CROSS = "SMALL_CROSS"
    SOLID = "SOLID"
    VERTICAL_CIRCLES = "VERTICAL_CIRCLES"
    VERTICAL_CIRCLES_WITH_DOTS = "VERTICAL_CIRCLES_WITH_DOTS"
    VERTICAL_DOTS = "VERTICAL_DOTS"
    VERTICAL_LINE = "VERTICAL_LINE"
    VERTICAL_LINES = "VERTICAL_LINES"
    VERTICAL_LINE_WITH_BIG_CROSS_INTERVAL = "VERTICAL_LINE_WITH_BIG_CROSS_INTERVAL"
    VERTICAL_LINE_WITH_HORIZONTAL_DASHED = "VERTICAL_LINE_WITH_HORIZONTAL_DASHED"
    VERTICAL_THICK_LINE = "VERTICAL_THICK_LINE"
    VERTICAL_TRIANGLES = "VERTICAL_TRIANGLES"
    VERTICAL_TRIANGLES_WITH_DOTS = "VERTICAL_TRIANGLES_WITH_DOTS"
    VERTICAL_TRIANGLES_WITH_VERTICAL_LINE = "VERTICAL_TRIANGLES_WITH_VERTICAL_LINE"

    def __str__(self) -> str:
        return str(self.value)
