from enum import Enum


class NadagSyncBlockerCode(str, Enum):
    MISSING_CLIENT = "MISSING_CLIENT"
    MISSING_CONTRACTOR = "MISSING_CONTRACTOR"
    MISSING_LOCATION_HEIGHT = "MISSING_LOCATION_HEIGHT"
    MISSING_LOCATION_POSITION = "MISSING_LOCATION_POSITION"
    MISSING_REPORT = "MISSING_REPORT"
    MISSING_USER_NADAG_ID = "MISSING_USER_NADAG_ID"
    PROJECT_BEFORE_NADAG_SYNC_CUTOFF = "PROJECT_BEFORE_NADAG_SYNC_CUTOFF"

    def __str__(self) -> str:
        return str(self.value)
