project_name_override: field-manager-python-client
package_name_override: field-manager-python-client
package_version_override: 4.4.90-rc.9
post_hooks:
  # - "bash -c 'cd field-manager-python-client && poetry install'"
