name: Release
on:
  workflow_dispatch: # This is a manual trigger
  release:
    types:
      - created

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.8.3"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: pypi
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Publish
        working-directory: field-manager-python-client
        run: |
          poetry publish --build
